### PR TITLE
Allow non-glob patterns with backslash on Windows

### LINKED ISSUE #105: fail to delete when used with path.join on windows
var pathTodelete = path.join('platforms', platform ,'app');
del.sync(pathToDelete]); // will do nothing even if the path does not have patterns

var pathTodelete = path.posix.join('platforms', platform ,'app');
del.sync(pathToDelete]);//works fine

del version 5.0.0
node version 10.16.2

### PR DESCRIPTION
**Pull request by chrisblossom**
This PR reverts the breaking change in `5.0.0` not allowing windows to pass direct paths to del making del easier to use on windows.

Fixes #105

### CODE REVIEW

**Comment by sindresorhus** [comment]
Yeah, this is a good middle ground.

Can you update the readme: https://github.com/sindresorhus/del#api

**Comment by chrisblossom** [comment]
I removed the note regarding backward slashes (basically reverted the change https://github.com/sindresorhus/del/commit/9e7550be045525afbd45bd7d591f3f539d48ca50). Is this what you wanted?

**Comment by sindresorhus** [comment]
I don't think we should remove the notes, as glob patterns *do* still need to only have forward slash. Just mention that normal file paths can have forward slashes.

**Comment by chrisblossom** [comment]
> Note that glob patterns can only contain forward-slashes, not backward-slashes. Windows file paths can use backward-slashes as long as the path does not contain any glob-like characters, otherwise use `path.posix.join()` instead of `path.join()`.

How does that sound?

**Comment by sindresorhus** [comment]
Perfect. Can you fix the merge conflict?

**Comment by chrisblossom** [comment]
Fixed!

**Pull request merged**
