### PR TITLE
Pass options to rimraf

### PR DESCRIPTION
**Pull request by chrisblossom**
I've wanted to add options to rimraf but haven't been able to.

This also defaults to use [`graceful-fs`](https://github.com/isaacs/node-graceful-fs#) to help prevent various fs errors. If this isn't wanted I can remove it.

### CODE REVIEW

**Comment by sindresorhus** [comment]
What do you need those options for? Actual use-cases? I have intentionally omitted them as I never saw the point and wanted to keep this module as simple as possible.

**Comment by chrisblossom** [comment]
I’ve encountered several errors on appveyor CI that would have been fixed if I could increase the limits and use graceful-fs instead of retrying the build.

**Comment by sindresorhus** [comment]
I'm happy to use `graceful-fs` here. That would solve your problem so we don't need to expose all these options, right?

**Comment by chrisblossom** [comment]
Another use-case would be to set custom sync functions that would "sync-back-off" to solve sync `emfileWait` / `maxBusyTries`. (Probably not a good idea for all use-cases (web-server), but others (webpack build) it would be nice). I'd probably experiment with this with [`clean-webpack-plugin`](https://github.com/johnagan/clean-webpack-plugin).

> That would solve your problem so we don't need to expose all these options, right?

I'm not 100% sure, but definitely is a good place to start.

When I was originally putting the PR in, I just wanted to be able to set the `maxBusyTries` and `emfileWait` options and `graceful-fs` so I figured I'd put all options available in and go from there.

Should I close this and add a new PR that just adds `graceful-fs`?

**Comment by sindresorhus** [comment]
> When I was originally putting the PR in, I just wanted to be able to set the maxBusyTries and emfileWait options and graceful-fs so I figured I'd put all options available in and go from there.

Instead of exposing a gadzillion options, I would prefer to first try to improve the defaults instead, if needed.

> Should I close this and add a new PR that just adds graceful-fs?

👍

**Comment by chrisblossom** [comment]
Closing in favor of #108.

**Pull request closed without merging**
