### PR TITLE
Fix `ProgressData#deletedCount`

### PR DESCRIPTION
**Pull request by liuhanqu**
`deletedCount` should start from `1`

### CODE REVIEW

**Comment by sindresorhus** [comment]
// @jopemachine

**Review by jopemachine — CHANGES_REQUESTED** [review]
Thanks for correcting this :)
It was my mistake when occurred in changing the call order of `onProgress`.

The below function call should be removed since the last element will be called twice by the line.

https://github.com/sindresorhus/del/blob/7fbeca0d2e0e065d7c2624638eb0c2e8bcadc25f/index.js#L99-L103

**Review by jopemachine — CHANGES_REQUESTED** [review]
And I think using `fileIndex` as mapper's argument here was another mistake.
`deletedCount` should be in ascending order semantically, but because `onProgress` is async, it will be called in order the promise resolve.

It means the below test will break.
https://github.com/sindresorhus/del/blob/7fbeca0d2e0e065d7c2624638eb0c2e8bcadc25f/test.js#L381

I think probably this should be fixed with like below codes.

```js
let fileIndex = 1;
const mapper = async (file) => {
// ...
	onProgress({
			totalCount: files.length,
			deletedCount: fileIndex,
			percent: fileIndex / files.length
	});
	++fileIndex;
// ...
}
```

**Comment by liuhanqu** [comment]
```javascript
let count  = 0
const mapper = async (file, fileIndex) => {
    file = path.resolve(cwd, file);

    if (!force) {
	safeCheck(file, cwd);
    }

    if (!dryRun) {
	await rimrafP(file, rimrafOptions);
    }

    count += 1

    onProgress({
	  totalCount: files.length,
	  deletedCount: count,
	  percent: count / files.length
    });

    return file;
};

```

Agree your point, but i think we should replace `fileIndex` with `count` while it's more semantic.

**Comment by jopemachine** [comment]
> Agree your point, but i think we should replace `fileIndex` with `count` while it's more semantic.

I agree the variable needs be renamed, but I think just using `deletedCount` would be better. (and `fileIndex` should be removed.)

**Comment by liuhanqu** [comment]
In the doc, the `onProgress` arguments is not the same in the code.
```js
{
	totalFiles: number,
	deletedFiles: number,
	percent: number
}
```

`xxxFiles` or `xxxCount`, which one ?

**Comment by jopemachine** [comment]
Thanks for correcting.

That should be `xxxCount`.

**Review by jopemachine — APPROVED** [review]

**Comment by jopemachine** [comment]
@sindresorhus
I'm sorry for the mess.
I will be more careful in handling feedback.

**Comment by sindresorhus** [comment]
Thanks, everyone :)

**Pull request merged**
