### PR TITLE
sequentially run rimraf in async mode

### PR DESCRIPTION
**Pull request by schnittstabil**
Instead of running `rimraf` on all files simultaneously, this PR returns back to the behavior of 1.x versions.

### CODE REVIEW

**Comment by TrySound** [comment]
@schnittstabil And why?

**Comment by schnittstabil** [comment]
@TrySound This fixes #43.

**Comment by schnittstabil** [comment]
@TrySound Maybe my comment was misleading, it's still using promises.

**Comment by sindresorhus** [comment]
Wonder if there's any other way to fix #43. Running things in serial will have a big performance hit. Race conditions doesn't really matter much here as we're deleting stuff, two things can try to delete the same thing and it doesn't really matter. We just need to handle the errors better.

**Comment by schnittstabil** [comment]
I would not like to handle `rimraf`s errors, because I'm afraid we may need to check if all files were deleted and may need to rerun `del`.

I'm not sure if it is a always a big performance hit: At least in the `test/**` case we start many `rimraf`s and each one called on a directory starts traversing it.

**Comment by schnittstabil** [comment]
We may sort the `files`, in that case directories are removed first (`rimraf` handles `ENOENT`).

**Comment by schnittstabil** [comment]
@dgreene1 @sindresorhus is the *Product Owner*, so it is up to him to decide on that. ATM it is unlikely, because we  [consider to handle the errors](https://github.com/sindresorhus/del/pull/44#issuecomment-156712287).

**Comment by kevva** [comment]
> We may sort the files, in that case directories are removed first (rimraf handles ENOENT).

That might work but would also require to check if every file is a directory first. Why can't we just handle all `ENOENT` errors and treat them as success?

**Comment by schnittstabil** [comment]
Not reproducible anymore – see #43.

**Pull request closed without merging**
